/** Verify NPC voicing end to end: pre-generated clip lookup, realtime
 *  KittenTTS synthesis in the worker (phonemizer + onnxruntime wasm), and a
 *  full say() with audio playback. */
import { chromium } from 'playwright';

const url = process.argv[2] ?? 'http://localhost:5199/?skip=1';
const browser = await chromium.launch({
  headless: true,
  args: ['--use-angle=swiftshader', '--disable-gpu-watchdog',
         '--autoplay-policy=no-user-gesture-required', '--js-flags=--max-old-space-size=4096'],
});
const page = await browser.newPage();
page.on('console', (m) => { if (m.type() === 'error' || m.type() === 'warning') console.log('[page]', m.text().slice(0, 160)); });
page.on('pageerror', (e) => console.log('[pageerror]', String(e).slice(0, 200)));

page.on('framenavigated', (f) => { if (f === page.mainFrame()) console.log('[nav]', f.url()); });
await page.goto(url, { waitUntil: 'domcontentloaded', timeout: 60000 });
await page.waitForFunction(() => window.__game?.npcs?.length > 0, null, { timeout: 180000, polling: 2000 });
await page.waitForTimeout(4000);   // survive any late lowspec auto-reload

// 0. Esk's exact on-screen line (the user's repro): which tier serves it?
const esk = await page.evaluate(async () => {
  const { voiceClip } = await import('/src/character/VoiceBank.js');
  const t0 = performance.now();
  const clip = await voiceClip('pedlar-esk',
    'Everything on this cloth is honest. The cloth is stolen. I find people prefer knowing which is which.');
  return clip
    ? { ok: true, tier: clip.url.startsWith('blob:') ? 'realtime' : 'pregen', dur: +clip.dur.toFixed(2), ms: Math.round(performance.now() - t0) }
    : { ok: false, ms: Math.round(performance.now() - t0) };
});
console.log('esk line:', JSON.stringify(esk));

// 0b. Does Esk's face attach for lipsync?
const face = await page.evaluate(async () => {
  const g = window.__game;
  const npc = g.npcs.find((n) => n.def?.id === 'pedlar-esk');
  if (!npc?.char) return { ok: false, why: 'no esk' };
  try { await npc.char.enableFace(); return { ok: true, hasFace: npc.char.hasFace }; }
  catch (e) { return { ok: false, why: String(e).slice(0, 120) }; }
});
console.log('esk face:', JSON.stringify(face));

// 1. Pre-generated lookup for a line that is in the manifest.
const pregen = await page.evaluate(async () => {
  const { voiceClip } = await import('/src/character/VoiceBank.js');
  const clip = await voiceClip('charles', "Ground's still there. That'll do for a Tuesday.");
  if (!clip) return { ok: false };
  const head = await fetch(clip.url).then((r) => r.status).catch(() => 0);
  return { ok: true, url: clip.url.slice(0, 60), dur: clip.dur, fetch: head };
});
console.log('pregen clip:', JSON.stringify(pregen));

// 2. Realtime synthesis of a line no manifest knows.
const live = await page.evaluate(async () => {
  const t0 = performance.now();
  const { voiceClip } = await import('/src/character/VoiceBank.js');
  const clip = await voiceClip('charles', 'This exact sentence was never pre-generated by anyone.');
  return clip
    ? { ok: true, url: clip.url.slice(0, 40), dur: +clip.dur.toFixed(2), ms: Math.round(performance.now() - t0) }
    : { ok: false, ms: Math.round(performance.now() - t0) };
});
console.log('realtime synth:', JSON.stringify(live));

// 3. Full say() on an NPC: pregen line, then novel line.
const say = await page.evaluate(async () => {
  const g = window.__game;
  const npc = g.npcs.find((n) => n.def?.id === 'charles');
  if (!npc?.char) return { ok: false, why: 'no charles' };
  const t0 = performance.now();
  await npc.char.say('A fresh line, spoken live.', { mood: 0.2 });
  return { ok: true, ms: Math.round(performance.now() - t0), speaking: npc.char.animator.speaking };
});
console.log('say():', JSON.stringify(say));

await browser.close();
